[package]
name = "hudmon"
version = "0.1.0"
edition = "2021"
description = "Minimalistyczny retro overlay: FPS / CPU / GPU / RAM (Windows + Linux)"

[lib]
name = "hudmon"
path = "src/lib.rs"

[[bin]]
name = "hudmon-overlay"
path = "src/main.rs"

[[bin]]
name = "hudmon"
path = "src/bin/hudmon.rs"

[dependencies]
sysinfo = { version = "0.30", default-features = false }
nvml-wrapper = "0.9"
winit = "0.29"
softbuffer = "0.4"
font8x8 = { version = "0.3", default-features = false, features = ["std"] }
image = { version = "0.25", default-features = false, features = ["ico"] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging"] }

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
